### ISSUE TITLE
Drawing a shape zoomed in then zooming out and drawing a shape removes original shape

### ISSUE THREAD

**Issue by ventralnet** [Wildhoney/Leaflet.FreeDraw#106]
https://jsfiddle.net/4qw5djw4/

1. Zoom in on an area as far as you can.  Draw a small shape.
2. Zoom as far out as you can and draw a shape
3. Notice the original shape you drew when zoomed in disappears

I assume this is a bug in the polygon merging/simplification

**Comment by Wildhoney** [comment]
Yep, that's a tough one, because I presume what's happening is that the first polygon is being removed, because at the zoomed out level it's considered to be too small, and thus removing in or drastically simplifying it.

You can see a slightly more subtle version of the same problem by zooming out only slightly.

**Comment by ventralnet** [comment]
Is there a way to disable simplification altogether, but to keep the polygon merging functionality?

**Comment by Wildhoney** [comment]
Nothing like that at the moment @ventralnet &mdash; only the `mergePolygons` option which is all or nothing.

**Comment by Wildhoney** [comment]
Published as `v2.6.0` @ventralnet.

Although the Leaflet intersection is somewhat rudimentary because it only works on rectangles &ndash; lat/lng bounds, so there are edge cases. However for the most part this fixes the issue you outlined 👍 

I will make an improvement to the intersect detector by using something like [Terraformer](http://terraformer.io/core/).

**Comment by Wildhoney** [comment]
`v.2.7.0` has improved intersection logic 👍 Thanks for the issue @ventralnet
