### ISSUE TITLE
Provide the ability to run hull algorithm asynchronously

### ISSUE THREAD

**Issue by chriserickson** [Wildhoney/Leaflet.FreeDraw#49]
If you draw something that takes a long time (1-3 seconds) to run the hull algorithm, it appears the browser is hung.

An event firing before and after processing might help, but I think would be insufficient -- I tried just adding these and there is not enough time for the DOM to update and put up a loading mask before hanging on the hull algorithm.

We were able to hack around the issue with the following code:

(forgive the coffeescript)

```
        # Adding the processing class doesn't give enough time
        # to re-draw the DOM before the hull algorithm locks up the browser...
        # To get IE 11 to re-render the DOM, it appears the timeout for the class change -> createMouseUp needs to be
        # at least 20 ms.
        # The RECOUNT_TIMEOUT needs to be bigger than this delay to make the 'markers' event fire after our
        # delayed createMouseUp
        L.FreeDraw.RECOUNT_TIMEOUT = 30
        @freeDrawer._createMouseUp = =>
            @$outerMapContainer.addClass('processing') if @freeDrawer.creating
            setTimeout (=>
                freeDrawerCreateMouseUp.apply(@freeDrawer, arguments)
                @$outerMapContainer.removeClass('processing')
            ), L.FreeDraw.RECOUNT_TIMEOUT - 5
```

It would be nice if FreeDraw could do one of the following:
a) provide events and run the hull algorithm on a timeout to allow the DOM to be masked
b) (even better) run the hull algorithm on a web worker to allow the DOM to be responsive while processing.

Note: I've found the most effective shape to make the hull algorithm run slow is a flower shape.

**Comment by fplgusmao** [comment]
I'm using FreeDraw in my project, and the algorithm can take ages (and I really mean ages)! I've discovered that the longer you take to draw the shape, the longer it takes to render it...

Note that, in the [heroku example](http://freedraw.herokuapp.com), this problem is not so bad, though you can still notice it (I'm probably adding too much crap to my app, but it doesn't matter much here).

Does this makes sense? Maybe we need to review the algorithm in order to make it kinda "time independent", contrary to the current case.

Anyway, your ideia is good... I'd vote for, at least, display a "loading" circle or something to let the user know the polygon is being drawn.

**Comment by Wildhoney** [comment]
Agreed that it would be nice to make the algorithm asynchronous with a Web Worker, but with the way it's coded it's not an easy task to separate that. I'll certainly take a look and see what can be done :+1:

**Comment by Wildhoney** [comment]
Will consider implementing in https://github.com/Wildhoney/Leaflet.FreeDraw/issues/76
