### ISSUE TITLE
Touch does not work

### ISSUE THREAD

**Issue by chriserickson** [Wildhoney/Leaflet.FreeDraw#50]
I've been unable to figure out how to get freedraw to work on a touch input device, whether iPad or Chrome with the touch device emulator.

No idea what the underlying problem is.

**Comment by Wildhoney** [comment]
Yep, there's an open issue for this that I haven't got around to yet: https://github.com/Wildhoney/Leaflet.FreeDraw/issues/3

`FreeDraw` doesn't currently have the necessary events setup to allow this. There are certain considerations to be made as well, since any click events won't be as precise as on a desktop.

Happy to hear people's opinions on this though, and then I can begin planning it out.

**Comment by chriserickson** [comment]
Ugh, sorry for the duplicate. I kept searching for 'touch' and was finding nothing....

**Comment by Wildhoney** [comment]
No problem :+1: Quite a few people have asked for it, so it would be nice to make some headway with it.

**Comment by alessiogaronzi** [comment]
At 2019 FreeDraw not work on Chrome in mobile. There are news?
