### ISSUE TITLE
Support conventional polygon click mode

### ISSUE THREAD

**Issue by jekuno** [Wildhoney/Leaflet.FreeDraw#52]
Currently the polygon can be drawn by holding down the mouse button.
Releasing it closes the polygon.

I would prefer if the tool would start in a conventional _polygon click mode_
which allows to create polygon points (and therefore edges)
by clicking at several points one after another.
As soon as the user holds down the mouse button the _FreeDraw mode_ gets activated.
If he releases the mouse button he can continue in the basic polygon click mode.
Doubleclick closes the polygon.

IMHO this would improve usability a lot as the user can easily combine
drawing _and_ clicking to create a polygon. This feature could be made optional
via L.FreeDraw.Options.

**Comment by Wildhoney** [comment]
Agreed it is a *nice to have* feature, but in creating `Leaflet.FreeDraw`, I didn't want to step on the toes of the [`Leaflet.draw` module](https://github.com/Leaflet/Leaflet.draw). With a combination of `Leaflet.FreeDraw` and `Leaflet.draw` you could definitely achieve something similar by activating/deactivating the layers as necessary :+1:

**Comment by jekuno** [comment]
Thanks for your fast answer.

I understand your point. I think `FreeDraw` doesn't step on the toes of the `Leaflet.draw` module.
`Leaflet.draw` provides tools which go far beyond polygon creation.
But for people who need FreeDraw functionality `Leaflet.FreeDraw` is the no 1 choice.

As far as I can see your FreeDraw plugin already provides everything to handle
basic "on click polygon creation" (IMHO building a polygon is not more than
pushing one point after another to the latLngs array).
The only addition would be to change some event handling in FreeDraw
(e.g. do not close and draw the polgon on mouseUp).

**Comment by Wildhoney** [comment]
I still don't agree that this should be part of `FreeDraw` because it is potentially far-reaching:

* Adding polygon edges as you click, as you do in `Leaflet.draw`, whereas `FreeDraw` doesn't have any notion of edges whilst drawing;
* Drawing of straight lines in between each click, when `FreeDraw` doesn't *know* what a straight line is. Currently each `latLng` is pushed into the `latLngs[]` array on the `mousemove` event, as you pointed out.

However, I do believe that you should be able to tweak JS apps as much as you like &ndash; even to the point of where you could potentially break them by passing bizarre values.

![Sharp Edges](http://www.newsrealblog.com/wp-content/uploads/2011/02/sharp-edges.jpg)

Ergo... I have allowed you to pass in the event names to the `options.setEvents` method. I've had a quick play around with the following values which seem to do something similar to what you're after:

```javascript
/* ... */
freeDraw.options.setEvents(['mousedown', 'mouseup', 'dblclick']);
```

As the `dblclick` event is bound to zooming in Leaflet (its a default binding), you'll need to disable that when instantiating the map (or afterwards &ndash; your choice):

```javascript
let map = new L.Map(element[0], { doubleClickZoom: false });
/* ... */
```

Happy experimenting! Try not to shoot yourself in the foot :+1: It's none too pleasant.

**Comment by jekuno** [comment]
@Wildhoney Thanks for this. I'm right now experimenting with this again and will report back if I got it working. :)

**Comment by agrimgupta92** [comment]
It seems like this functionality is not longer present. Can you please guide as to how to achieve the same in the current version?

**Comment by Wildhoney** [comment]
No way in the *new* version. Will add it to the roadmap 👍
