### ISSUE TITLE
Dealing with point creation

### ISSUE THREAD

**Issue by stev-0** [Wildhoney/Leaflet.FreeDraw#60]
I suspect I know the answer to this based on the readme, but what is the opinion on extending Leaflet.FreeDraw to deal with point creation? I assume this isn't at all on the project's roadmap. I guess I could attempt to add it myself, but it does seem like something that would be easier to do through Leaflet.Editable (part of the reluctance for using Leaflet.Draw is that there are a large number of outstanding pull requests, so not sure whether the project has stagnated). Then you would add and edit points through Leaflet Editable, Polygons through Leaflet.FreeDraw and lines through Leaflet.Pather. Or is that totally insane?

By the way, kudos for creating this, it's great. I just think the UI is much for natural for people who are not used to GIS.

**Comment by Wildhoney** [comment]
Thanks @stev-0 !

That does sound quite insane, but fair play to you if you're going to attempt that. You're right that it's not on the project's roadmap unfortunately. I think one module should shine at only one thing, and let other modules do their thing, and then combine them in your project. Otherwise the module becomes far too overreach and diluted.
