### ISSUE TITLE
Option to remove elbows?

### ISSUE THREAD

**Issue by emakarov** [Wildhoney/Leaflet.FreeDraw#61]
There's an option to attach elbows, but how to make an option to remove them?
Sometimes it's required to remove edges as well.
I also detected that when editing the polygon, it's possible to remove elbows that were created on click after initial draw. But not "original" elbows

**Comment by Wildhoney** [comment]
@emakarov Elbows are **always** attached, but are only visible when the `L.FreeDraw.MODES.EDIT` bit is set. How would removing an edge work? Since that would essentially destroy the polygon.

How would I replicate the issue where elbows are removed? I'm only aware of elbows being removed where it's a *pointless* elbow, because the line is straight from A to C, and therefore elbow B would be redundant, and therefore removed.

**Comment by emakarov** [comment]
I will close issue for a while, also cannot reproduce the bug

**Comment by Wildhoney** [comment]
Thanks @emakarov let me know if you encounter it again.
