### ISSUE TITLE
Use without webpack/angular

### ISSUE THREAD

**Issue by sainsb** [Wildhoney/Leaflet.FreeDraw#81]
How would I use this without webpack/angular? I feel like you're getting too fancy for a lot of your audience...(but your work is greatly appreciated)

**Comment by Wildhoney** [comment]
@sainsb I hear what you're saying. Although in my defence I would like to say that the example has **always** been written in Angular &ndash; it's not something I changed with `v2.0.0`.

I'm not the biggest fan of Webpack by a long way, as I believe it's significantly overstepping the mark with `import`ing things like CSS, images, etc... when `import` is solely for JavaScript.

With that said though, we do have a [compiled version for the web](https://github.com/Wildhoney/Leaflet.FreeDraw/blob/master/dist/leaflet-freedraw.web.js) without Webpack, and I've set you up an example on JSFiddle for how to use it without Webpack: https://jsfiddle.net/vry9e6kd/ With this example, the `freeDraw` will have [all of the functions](https://github.com/Wildhoney/Leaflet.FreeDraw#methods) for interacting with the layer, as well as the events. Angular doesn't add anything special.

There are a couple of things I need to work on, however:

- Reduce the filesize of the web version by externalising some of the resources.
- Remove the quirk of having to instantiate `FreeDraw.default` rather than simply `FreeDraw`.
- Minify the web version which would currently clock it in at 473KB because of D3, ClipperLib and Ramda &ndash; I'm sure I could further reduce this.

`FreeDraw` is also still on Bower:

```
Available versions:
  - 2.0.0
  - etc...
```

Please let me know if you need any further help @sainsb

**Comment by Wildhoney** [comment]
I've updated the dependencies, minified the output for the web, and made it `new FreeDraw` rather than `new default.FreeDraw`. For the output we're down to 267KB, and 75.4KB with GZIP compression level 6.

JSFiddle updated: https://jsfiddle.net/sxgwtnhk/1/ 👍

**Comment by sainsb** [comment]
Aha, I think I got a little misled by the examples. calling the constructor with `new FreeDraw.default ({ mode: FreeDraw.ALL})` was not obvious.  Sorry to be whiney.  this module really is awesome.
